import { useEffect, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { createRoot } from "react-dom/client";
import "./styles.css";

const API = "http://localhost:4000/api/v1";
const request = async (path: string, options: RequestInit = {}) => {
  const token = localStorage.getItem("parkops-token");
  const response = await fetch(`${API}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error?.message ?? "Request failed.");
  return data;
};
const money = (paise: number) => `₹${(paise / 100).toFixed(2)}`;

function Auth({ register = false }: { register?: boolean }) {
  const navigate = useNavigate(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const f = new FormData(event.currentTarget); try { const body = register ? { name: f.get("name"), email: f.get("email"), password: f.get("password"), garageName: f.get("garage"), garageAddress: f.get("address") } : { email: f.get("email"), password: f.get("password") }; const data = await request(`/auth/${register ? "register" : "login"}`, { method: "POST", body: JSON.stringify(body) }); localStorage.setItem("parkops-token", data.token); navigate("/app/dashboard"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to continue."); } finally { setBusy(false); } }
  return <main className="auth"><Link className="logo" to="/"><b>P</b>ParkOps</Link><form onSubmit={submit}><small>{register ? "CREATE GARAGE" : "OPERATOR LOGIN"}</small><h1>{register ? "Launch your terminal." : "Welcome back."}</h1>{register && <><Field label="Your name" name="name"/><Field label="Garage name" name="garage"/><Field label="Garage address" name="address"/></>}<Field label="Email" name="email" type="email"/><Field label="Password" name="password" type="password" minLength={8}/>{error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? "Working…" : register ? "Create garage" : "Log in"}</button><p>{register ? "Already registered?" : "New to ParkOps?"} <Link to={register ? "/login" : "/register"}>{register ? "Log in" : "Create a garage"}</Link></p></form></main>;
}
function Field({ label, name, ...props }: { label: string; name: string; type?: string; minLength?: number }) { return <label>{label}<input name={name} required {...props}/></label>; }

function Shell({ children }: { children: ReactNode }) { const location = useLocation(); const navigate = useNavigate(); const nav = (path: string, label: string) => <Link className={location.pathname === path ? "selected" : ""} to={path}>{label}</Link>; return <div className="shell"><aside><Link className="logo" to="/app/dashboard"><b>P</b>ParkOps</Link><small>TERMINAL OS V2.4</small><section className="garage"><span>ASSIGNED GARAGE & LOCATION</span><strong>Garage #4 Central</strong><em>● ENTRY / EXIT AUTO</em></section><nav>{nav("/app/dashboard", "▦  Dashboard")}{nav("/app/check-in", "↪  Check-In")}{nav("/app/checkout", "⇥  Check-Out & Exit")}{nav("/app/lookup", "⌕  Vehicle Lookup")}{nav("/app/history", "▤  Parking History")}{nav("/app/rates", "⚙  Rates & Settings")}</nav><section className="operator"><b>Rajesh K.</b><small>Shift B · 08:00–16:00</small><strong>₹4,850.00</strong></section><button className="signout" onClick={() => { localStorage.removeItem("parkops-token"); navigate("/"); }}>Sign out</button></aside><div className="workarea"><header className="topbar"><span>FASTag & Sensor Gateway: <b>Synced (12ms)</b></span><span>● Online</span></header>{children}</div></div>; }
function Guard({ children }: { children: ReactNode }) { return localStorage.getItem("parkops-token") ? <Shell>{children}</Shell> : <Navigate to="/login" replace/>; }

function CheckIn({ compact = false }: { compact?: boolean }) { const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const f = new FormData(event.currentTarget); try { const data = await request("/parking/check-in", { method: "POST", body: JSON.stringify({ plateNumber: f.get("plate"), vehicleType: f.get("vehicleType") }) }); setMessage(`${data.session.plateNumber} assigned: Floor ${data.spot.floor}, ${data.spot.number}.`); event.currentTarget.reset(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Check-in failed."); } finally { setBusy(false); } } return <section className={`panel checkin ${compact ? "compact" : ""}`}><div className="panel-heading"><div><small>PRIMARY OPERATION</small><h2>Express ingress check-in</h2></div><span>● ANPR Lane 01</span></div><form onSubmit={submit}><label>License plate<input name="plate" placeholder="RJ14 AB-1234" required/></label><label>Vehicle type<select name="vehicleType"><option value="STANDARD">Standard</option><option value="COMPACT">Compact</option><option value="EV">EV — charger required</option></select></label><button className="primary" disabled={busy}>{busy ? "Assigning…" : "Auto-assign bay & raise"}</button></form>{message && <p className="success">✓ {message}</p>}{error && <p className="error">{error}</p>}</section>; }

function Dashboard() { const [summary, setSummary] = useState<any>(); const [active, setActive] = useState<any[]>([]); const [error, setError] = useState(""); const load = async () => { try { const [s, a] = await Promise.all([request("/dashboard/summary"), request("/parking/active?pageSize=5")]); setSummary(s); setActive(a.items); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load dashboard."); } }; useEffect(() => { load(); }, []); return <Page title="Operations dashboard" action={<button className="secondary" onClick={load}>Refresh data</button>}>{error && <p className="error">{error}</p>}<section className="metrics"><Metric label="TOTAL OCCUPANCY" value={summary ? `${summary.occupiedSpots}/${summary.totalSpots}` : "—"} note="Levels 1–3 active"/><Metric label="EV CHARGER BANKS" value={summary ? `${summary.evAvailable}/${summary.evTotal}` : "—"} note="Stalls free" accent/><Metric label="ACTIVE FLEET" value={summary?.activeSessions ?? "—"} note="Vehicles live"/><Metric label="SHIFT COLLECTION" value="₹28,450" note="UPI · Cash · RFID"/></section><div className="dashboard-grid"><CheckIn compact/><ActiveTable items={active} onChanged={load}/><section className="panel rail"><h2>EV Charger Deck</h2><b>{summary?.evAvailable ?? "—"} free</b><div className="ev-grid">{Array.from({ length: 12 }, (_, i) => <span key={i} className={i < 3 ? "charging" : i === 10 ? "fault" : ""}>E{i + 1}</span>)}</div><small>Blue: charging · Grey: free · Red: service</small></section></div></Page>; }
function Metric({ label, value, note, accent }: { label: string; value: string | number; note: string; accent?: boolean }) { return <article className={`metric ${accent ? "accent" : ""}`}><small>{label}</small><b>{value}</b><span>{note}</span><i/></article>; }
function ActiveTable({ items, onChanged }: { items: any[]; onChanged: () => void }) { const [error, setError] = useState(""); async function checkout(id: string) { try { await request(`/parking/${id}/check-out`, { method: "POST", body: "{}" }); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Checkout failed."); } } return <section className="panel fleet"><div className="panel-heading"><div><small>LIVE FLOOR</small><h2>Active fleet</h2></div><Link to="/app/lookup">Search vehicles →</Link></div>{error && <p className="error">{error}</p>}<table><thead><tr><th>PLATE</th><th>TYPE</th><th>BAY</th><th>ENTRY</th><th/></tr></thead><tbody>{items.length ? items.map(x => <tr key={x.id}><td><b>{x.plateNumber}</b></td><td>{x.vehicleType}</td><td>F{x.spot.floor}-{x.spot.number}</td><td>{new Date(x.checkedInAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</td><td><button onClick={() => checkout(x.id)}>Settle</button></td></tr>) : <tr><td colSpan={5} className="empty">No live vehicles yet.</td></tr>}</tbody></table></section>; }
function Lookup({ checkout = false }: { checkout?: boolean }) { const [plate, setPlate] = useState(""); const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [transfer, setTransfer] = useState<Record<string, string>>({}); async function search(event: FormEvent) { event.preventDefault(); try { const d = await request(`/parking/search?plate=${encodeURIComponent(plate)}`); setItems(d.items); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Lookup failed."); } } async function settle(id: string) { try { await request(`/parking/${id}/check-out`, { method: "POST", body: "{}" }); setItems([]); setPlate(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Checkout failed."); } } async function transferPlate(id: string) { try { const data = await request(`/parking/${id}/transfer-plate`, { method: "POST", body: JSON.stringify({ plateNumber: transfer[id] }) }); setItems(items.map(item => item.id === id ? data.session : item)); setTransfer({ ...transfer, [id]: "" }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Plate transfer failed."); } } return <Page title={checkout ? "Check-out & exit" : "Vehicle lookup"}><section className="panel lookup"><p>Search an active vehicle by normalized plate number.</p><form onSubmit={search}><input value={plate} onChange={e => setPlate(e.target.value)} placeholder="RJ14 AB-1234" required/><button className="primary">Find vehicle</button></form>{error && <p className="error">{error}</p>}{items.map(x => <article className="result" key={x.id}><div><b>{x.plateNumber}</b><span>{x.vehicleType} · Floor {x.spot.floor}, {x.spot.number}</span>{!checkout && <div className="transfer"><input value={transfer[x.id] ?? ""} onChange={e => setTransfer({ ...transfer, [x.id]: e.target.value })} placeholder="New plate for valet hand-off"/><button className="secondary" disabled={!transfer[x.id]} onClick={() => transferPlate(x.id)}>Transfer plate</button></div>}</div>{checkout && <button className="primary" onClick={() => settle(x.id)}>Checkout & settle</button>}</article>)}</section></Page>; }
function History() { const [items, setItems] = useState<any[]>([]); const [search, setSearch] = useState(""); const [sortBy, setSortBy] = useState("checkedOutAt"); const [sortOrder, setSortOrder] = useState("desc"); const [page, setPage] = useState(1); const [pagination, setPagination] = useState<any>(); const [error, setError] = useState(""); async function load(event?: FormEvent, nextPage = page) { event?.preventDefault(); try { const d = await request(`/parking/history?search=${encodeURIComponent(search)}&page=${nextPage}&pageSize=10&sortBy=${sortBy}&sortOrder=${sortOrder}`); setItems(d.items); setPagination(d.pagination); setPage(nextPage); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load history."); } } useEffect(() => { load(undefined, 1); }, [sortBy, sortOrder]); return <Page title="Parking history"><section className="panel history"><form onSubmit={event => load(event, 1)}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by plate"/><select value={sortBy} onChange={e => setSortBy(e.target.value)}><option value="checkedOutAt">Checkout time</option><option value="checkedInAt">Check-in time</option><option value="plateNumber">Plate</option><option value="feePaisa">Fee</option></select><select value={sortOrder} onChange={e => setSortOrder(e.target.value)}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select><button className="secondary">Search</button></form>{error && <p className="error">{error}</p>}<table><thead><tr><th>PLATE</th><th>SPOT</th><th>CHECKED OUT</th><th>FEE</th></tr></thead><tbody>{items.length ? items.map(x => <tr key={x.id}><td><b>{x.plateNumber}</b></td><td>F{x.spot.floor}-{x.spot.number}</td><td>{new Date(x.checkedOutAt).toLocaleString()}</td><td>{money(x.feePaisa)}</td></tr>) : <tr><td colSpan={4} className="empty">No completed sessions yet.</td></tr>}</tbody></table>{pagination && <footer className="pager"><span>Page {pagination.page} of {pagination.totalPages || 1} · {pagination.total} sessions</span><button className="secondary" disabled={page <= 1} onClick={() => load(undefined, page - 1)}>Previous</button><button className="secondary" disabled={page >= pagination.totalPages} onClick={() => load(undefined, page + 1)}>Next</button></footer>}</section></Page>; }
function Rates() { const [raw, setRaw] = useState("COMPACT, 50, 30, 250\nSTANDARD, 50, 30, 250\nEV, 60, 40, 300"); const [message, setMessage] = useState(""); const [error, setError] = useState(""); async function importRates(event: FormEvent) { event.preventDefault(); try { const d = await request("/rates/import", { method: "POST", body: JSON.stringify({ rawRateCard: raw }) }); setMessage(`Imported ${d.accepted.length} cleaned rate types.`); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Rate import failed."); } } return <Page title="Rates & garage settings"><section className="panel rates"><p>Paste one row per spot type: type, first hour, additional hour, daily cap. Junk rows are rejected.</p><form onSubmit={importRates}><textarea value={raw} onChange={e => setRaw(e.target.value)} rows={7}/><button className="primary">Clean & import rate card</button></form>{message && <p className="success">✓ {message}</p>}{error && <p className="error">{error}</p>}</section></Page>; }
function Page({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <main className="page"><header className="page-header"><div><small>GARAGE #4 CENTRAL / OPERATIONS</small><h1>{title}</h1></div>{action}</header>{children}</main>; }
function Landing() { return <main className="landing"><Link className="logo" to="/"><b>P</b>ParkOps</Link><section><small>ATTENDANT-FIRST PARKING OPERATIONS</small><h1>Every vehicle.<br/><em>The right spot.</em><br/>The right fee.</h1><p>ParkOps is the operations terminal for busy multi-level garages. It helps parking attendants move cars quickly while keeping allocation, occupancy, and billing correct.</p><div className="landing-actions"><Link className="primary" to="/register">Create your garage</Link><Link className="text-link" to="/login">Log in</Link></div><div className="landing-details"><article><b>Check in with confidence</b><span>Automatic, deterministic compatible-bay allocation prevents double parking.</span></article><article><b>Charge accurately</b><span>Server-owned tiered rates, hourly rounding, daily caps, and per-spot-type rate cards.</span></article><article><b>Find and settle fast</b><span>Live plate lookup, EV availability, checkout, and searchable historical sessions.</span></article></div><div className="future-features"><small>NEXT THREE FEATURES</small><ol><li>Reservation-aware bay allocation</li><li>Receipt payments and reconciliation</li><li>Live multi-attendant updates</li></ol></div></section></main>; }
function App() { return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/app/dashboard" element={<Guard><Dashboard/></Guard>}/><Route path="/app/check-in" element={<Guard><Page title="Check-in"><CheckIn/></Page></Guard>}/><Route path="/app/checkout" element={<Guard><Lookup checkout/></Guard>}/><Route path="/app/lookup" element={<Guard><Lookup/></Guard>}/><Route path="/app/history" element={<Guard><History/></Guard>}/><Route path="/app/rates" element={<Guard><Rates/></Guard>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>; }
createRoot(document.getElementById("root")!).render(<BrowserRouter><App/></BrowserRouter>);
